"""Add on delete casecade

Revision ID: 72b8e0ca0d88
Revises: f2fdc7609bf6
Create Date: 2025-05-15 10:45:34.726609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b8e0ca0d88'
down_revision: Union[str, None] = 'f2fdc7609bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todos_created_by_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_created_by_fkey', 'todos', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
