"""Add updated_at to users

Revision ID: f2fdc7609bf6
Revises: 4e8d287ec406
Create Date: 2025-05-13 12:14:06.816104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fdc7609bf6'
down_revision: Union[str, None] = '4e8d287ec406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'is_administration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_administration', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
